language: node_js
sudo: required # to install newer g++ :(
node_js:
- "4.0.0"
- "0.12"
- "0.11"
- "0.10"
script:
- |
  echo "machine github.com login stellar-jenkins password $GITHUB_TOKEN" >~/.netrc
  git config --global user.name "Travis CI"
  git config --global user.email "travis@stellar.org"
  gulp test && gulp build
before_install:
- npm install -g npm@'>=2.13.5'
- |
  mkdir -p .npm
  export DISPLAY=:99.0
  sh -e /etc/init.d/xvfb start
notifications:
  slack:
    secure: CgXxNEQrQ82EatyF/wSdF0P5rXcWPL+fFZ1lb1aBb8RbVt5gwddJ6xWVD/nYSr6tIJvIYHYhoYsIDPENwezIPsesG7kWXerQhydsEcA34JKxzsStd/TmU6Moxuwy6KTN7yzmL6586nSvoAw9TNPgvRkJFkH07asjGIc9Rlaq7/Y=
env:
  global:
    - secure: UfHc1SSKsUx8j2Z/S9WoJA+Qd9T9tWQZEGZVzmAmkGQ+V4iQsYwp2AwWJLH+e0JSKcVz9tiGicPfv8RlVS4YAQ2EeW2kC2W0ULrX4FYwNuuD/tjfHl47Vsoze4QlBuaZd897upt8r30GpUhqLonAkKr3700lZjr9Id3woWrSNfA=
    - CXX=g++-4.8 # node bindings in 4.0.0
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
deploy:
  - provider: npm
    email: npm@stellar.org
    api_key:
      secure: Vhs69f1et3b+U0tMAdViua2G4+dLapfMcMnAWn6EMSbzafgdBvObOIUP1Fo/NCp5jD236/zB/eV9Bs2y4tbgDLkSg+qUaKZnX2QIQ9CDCCEF8BMtLDLJTiDWBNrw5WJc/84f6tvEfFuMohnWkMBaGZ7dOgUL9ud2Ci/kDx1hoBY=
    skip_cleanup: true
    on:
      tags: true
      repo: stellar/js-stellar-base
  - provider: script
    script: ./bower_publish.sh
    skip_cleanup: true
    on:
      tags: true
      repo: stellar/js-stellar-base
