language: node_js
node_js:
- '0.10'
script:
- |
  if [ "$TEST_TYPE" = build_website ]; then
    if [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_PULL_REQUEST" = false ]; then
      set -e

      cd website
      npm install
      ./setup.sh
      echo "machine github.com login stellar-jenkins password $GITHUB_TOKEN" >~/.netrc
      git config --global user.name "Travis CI"
      git config --global user.email "travis@stellar.org"
      ./publish.sh
    fi
  else
    gulp $TEST_TYPE
  fi
before_install:
- |
  if [ "$TEST_TYPE" != build_website ]; then
    mkdir -p .npm
    export DISPLAY=:99.0
    sh -e /etc/init.d/xvfb start
  fi
notifications:
  slack:
    secure: CgXxNEQrQ82EatyF/wSdF0P5rXcWPL+fFZ1lb1aBb8RbVt5gwddJ6xWVD/nYSr6tIJvIYHYhoYsIDPENwezIPsesG7kWXerQhydsEcA34JKxzsStd/TmU6Moxuwy6KTN7yzmL6586nSvoAw9TNPgvRkJFkH07asjGIc9Rlaq7/Y=
env:
  matrix:
  - TEST_TYPE=test
  - TEST_TYPE=build_website
  global:
    secure: UfHc1SSKsUx8j2Z/S9WoJA+Qd9T9tWQZEGZVzmAmkGQ+V4iQsYwp2AwWJLH+e0JSKcVz9tiGicPfv8RlVS4YAQ2EeW2kC2W0ULrX4FYwNuuD/tjfHl47Vsoze4QlBuaZd897upt8r30GpUhqLonAkKr3700lZjr9Id3woWrSNfA=
deploy:
  - provider: npm
    email: npm@stellar.org
    api_key:
      secure: V9cJx+oDOJG1nhMiZrKUo52kW/bszqxfjbr1+cq2B2luRxh8X+6fdBFGySqvIj9/1TeqHo0rP7XIPhWPHvJ2q97a+/6G2JAnDi4XBiudLPpQmK9guFvUq4dq00sT43TvLSdNcXsnHIIEiRxw8JMc6ibQVvPr1yRZ5zGhVrutZ0M=
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: bower_publish.sh
    skip_cleanup: true
    on:
      tags: true
