language: node_js
node_js:
- '0.10'
script: gulp test
before_install:
- mkdir -p .npm
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
notifications:
  slack:
    secure: q2z7sQIuc3sqGnRoHdmbOBcsvvffK3abJRL+qd/7Kh0ET/BtN6QJqM5O2IZwttFiDjVF5+lyIU0VEHBGyGoru5ovyRl7aOW6kq2uxJqdZrZcsQqz2Uug1M0RZG/1wSG7E2MbRdO0UGoJUCWxmXxAIRdg/cD0zEgAPxBjPc4m+aQ=
